### ISSUE TITLE
Site very slow on local

### ISSUE THREAD

**Issue by ondrabus** [Kentico/kontent-starter-corporate-next-js#37]
### Brief bug description

After running the site locally with `npm run dev` on Windows 10 the site is very slow both on initial and subsequent loads. See attached gif.
Turning Windows Defender on/off does not affect this issue.

### Expected behavior

Site should be fast, pages load instantly.

### Test environment

 - Platform/OS: Windows 10
 - Browser: Chrome 89

### Screenshots

https://ibb.co/dcw9D7T

**Comment by Simply007** [comment]
@ondrabus  Does this slow start happens also for the second time? 
...If you abort the dev mode after the first run and restart it?

I have tested out these steps (stored in https://github.com/Kentico/kontent-starter-corporate-next-js/tree/issue/37)
* use webpack 5 https://nextjs.org/docs/messages/webpack5
* update Next.js to states version 10.1.3
* Material design adjustments might slow down the initial build - I have removed 
* removed direct import of whole lodash

Could you verify if the initial page load is still slow (something else is causing it). Or we could start to ad feature by feature and identify the root cause.

**Comment by Simply007** [comment]
A couple of other improvement trials that does not affect the application functionality:
* https://github.com/Kentico/kontent-starter-corporate-next-js/pull/40
