### ISSUE TITLE
Circular references in Kontent incompatible with NextJS

### ISSUE THREAD

**Issue by jordan-ghost** [Kentico/kontent-starter-corporate-next-js#52]
Hi,

I'm building a statically exported site for a client, who has built up a fairly large Kontent repository. As part of the content they wish to present, we have (among others) a 'Related Services' type of thing which enumerates the children of a linked Navigation Item. This works fine, however, there are a few instances where the client would like use this to show _siblings_ of the current item, by linking to it's parent navItem, like this:

![loop](https://user-images.githubusercontent.com/8196039/132447429-e89297f2-ab7f-460a-bc85-873a3f138dcc.png)

Therefore, there is a circular reference in the data structure returned by `DeliveryClient.mappingService.viewContentItemResponse`, which NextJS complains about ([with this error message](https://nextjs.org/docs/messages/circular-structure)).

I understand well why NextJS can't support circular data for static exports. However I'm still stuck trying to support the client's circular content.

I've tried deferring the hydration of the data later and later into the init process, moving it from `app.js` to `[[slug]].js` to right inside my Page components, but NextJS still wants it to be serialisable.

Do you have any recommendations for best practices for supporting circular content like this? My next approach will be to skip hydration, and pass the unmapped response to all components, fetching linked items from the `modular_content` array manually inside every component. This obviously requires rewriting most of the application, so if there's a more idiomatic way to do this, that would be a life saver.

Thanks for your assistance,
Jordan

**Comment by Simply007** [comment]
Hello @jordan-ghost,

> I didn't expect that sitemap itself would be modeled as a graph instead of the tree (haven't see a use case for it). It would be interesting to understand the benefit of doing this way rather than extending the Navigation item with i.e. `sublings` linked items element.

I have tried to reproduce your scenario by adding a circular reference to the model but I haven't encountered the same error you did. And I still think you can pass circular references if it is on the client as React proper (in _app component), you just can return them from `getStaticProps/getInitialProps`.

Instead of your error, I found another error after creating a circular reference in the model.

![image](https://user-images.githubusercontent.com/9218736/132540377-4bb64de4-f1ca-4a24-9ae6-9be7bf5201a2.png)

You can check the model under `22c0ab58-ad73-00a9-80aa-1b3a8815223d` project ID - it is basically a clone of the model for this starter with circular reference (and changed color theme to prevent me to make changes to production project).

And I was able to get this error:
```
RangeError: Maximum call stack size exceeded
    at getSubPaths (C:\projects\kontent-starter-corporate-next-js\.next\server\pages\_app.js:2181:11)
    at getSubPaths (C:\projects\kontent-starter-corporate-next-js\.next\server\pages\_app.js:2216:28)
    at getSubPaths (C:\projects\kontent-starter-corporate-next-js\.next\server\pages\_app.js:2216:28)
    at getSubPaths (C:\projects\kontent-starter-corporate-next-js\.next\server\pages\_app.js:2216:28)
    at getSubPaths (C:\projects\kontent-starter-corporate-next-js\.next\server\pages\_app.js:2216:28)
    at getSubPaths (C:\projects\kontent-starter-corporate-next-js\.next\server\pages\_app.js:2216:28)
    at getSubPaths (C:\projects\kontent-starter-corporate-next-js\.next\server\pages\_app.js:2216:28)
    at getSubPaths (C:\projects\kontent-starter-corporate-next-js\.next\server\pages\_app.js:2216:28)
    at getSubPaths (C:\projects\kontent-starter-corporate-next-js\.next\server\pages\_app.js:2216:28)
    at getSubPaths (C:\projects\kontent-starter-corporate-next-js\.next\server\pages\_app.js:2216:28) {
  type: 'RangeError'
}
```

But this error was caused by the `getSubPaths` method because this one does not check for circular references. I have made the adjustment to skip circular references and site is working:

Check #53 to see the changes I made.

If this is not your issue, could you adjust this starter as I did in #53 so that I can reproduce the issue, then I might be able to look into that.

**Comment by jordan-ghost** [comment]
Hi @Simply007, thanks again for your quick response :)

I see what you mean about breaking cycles in `getSubPaths`, I've tried this strategy too, but I think our problem is different than that. Our code has changed quite a lot since it started and I don't think I'll have time to recreate this scenario in the starter repo. I think our solution will be to just _not_ hydrate page data and provide `modular_content` as part of a global React Context or something.

Thanks for looking into it, I appreciate it :)

Cheers,
Jordan
